### ISSUE TITLE
Generate DB from schema.php file

### ISSUE THREAD

**Issue by aFaneca** [odan/phinx-migrations-generator#108]
Consider a situation where a schema.php file is already present, with all the correct entities and attributes, but the database is still empty.
If I currently choose to generate a new migration file, your software uses the database as the single source of truth, so the generated migration file will have instructions to drop all of the tables present in schema.php (since they are not present in the database).

Is there any flag I can use to choose the schema.php file as the source of truth and generate from that a migration file that, in turn, I can use to recreate an empty database (no entities) from it?

**Comment by odan** [comment]
The `schema.php` file contains all table- and column-definitions of the database after the new migration script has been generated.

Here you can find more information about the usage: https://github.com/odan/phinx-migrations-generator/issues/8#issuecomment-295460712

**Comment by aFaneca** [comment]
I understand that fully. My question is: can I use the schema.php has the base class to generate the migration file, instead of it being the DB itself?

Here's an example: let's say I have a DB with 3 well defined entities. Then, I use your software to generate an initial schema.php file which contains the definition of those 3 entities and their respective attributes.
Imagine that, then, I drop every table from that DB.

If I use your software to generate another migration, it will see that the schema file has 3 tables defined and the DB has none. Since the DB is the source of truth, it will generate a migration file with instructions to drop those tables.

My question is: is there anyway I can generate a migration file that uses the schema.php file as the source of truth instead? The migration file would then have all the necessary instructions to replicate in the DB the structure present in the schema.php.

**Comment by odan** [comment]
I'm not sure why you want to use the schemap.php as "source" and not the generated phinx migration class?

The idea behind phinx is to use the migration classes to migrate your database schema to the server.
This package is an "extension" that adds the missing "diff" command to phinx.
The `schema.php` file is just a "snapshot" to generate create a new migration class from the last status.

If you run all migration classes with phinx you are able to replicate the structure on any server.

The steps are:

* Create a database with the tables
* Generate a migration (class) using this package
* Commit this files to your version control
* Deploy your application to the server
* Run `vendor/bin/phinx migrate` to install or change the table structure

> is there anyway I can generate a migration file that uses the schema.php file as the source of truth instead?

No, because this is not the use case for this package.

>  The migration file would then have all the necessary instructions to replicate in the DB the structure present in the schema.php.

Conceptually, only the phinx migration classes are the "source" commands for your database changes.

**Comment by aFaneca** [comment]
> I'm not sure why you want to use the schema.php file as "source" and not the generated phinx migration class?
> 
> The idea behind phinx is to use the migration classes to migrate your database schema to the server. This package is an "extension" that adds the missing "diff" command to phinx. The `schema.php` file is just a "snapshot" to generate create a new migration class from the last status.
> 
> If you run all migration classes with phinx you are able to replicate the structure on any server.
> 
> The steps are:
> 
> * Create a database with the tables
> * Generate a migration (class) using this package
> * Commit this files to your version control
> * Deploy your application to the server
> * Run `vendor/bin/phinx migrate`

I understand if this out of scope in terms of your project, but I was thinking about a way of using migrations in 2 scenarios:

1. manage ongoing DB changes. Each new release has a set of migrations that I can run on production server to make the necessary schema changes 
2. automate initial setup (e.g. Installing self-hosted project in new environment) 

Scenario nr. 1 works as expected and your project helps out tremendously in that regard. 
My issue is with scenario nr.2. Initially, I thought I could generate an initial migration file that I would always keep in version control. Once I installed my project in a new machine, I could just run the migration and that would automatically generate my DB structure in that new machine. The thing is: if I keep that initial migration in the `db/migrations` directory and try to run the migrations in an environment where the DB schema already is setup, the script will fail, with an error saying **_"table xyz already exists"_**. 

So, right now, I follow these steps for a new setup:

1. Clone project to directory in server 
2. Deal with project-specific setup
3. Run an sql script that creates all the tables and attributes (that I manually generate from mysql workbench) 

Then, for each new version released:

1. Git pull 
2. Run phinx migrations (that only contains migrations brought by this last update, all others are previously deleted) 

I've been thinking of ways of improving this workflow, since it has a few issues:

1. Initial setup not as automated as I would of liked
2. If I update from version 2 straight to version 4 (example), I'll be in trouble, because the migrations folder will only contain migrations from v3 to v4 and not the ones from v2 to v3. That means I'll have to update incrementally, one version at a time to be sure everything will be OK. 

Again, I understand this is more related to phinx itself than anything else, but that was the use case I was thinking off.

**Comment by odan** [comment]
The question is, why invent such a complex use case when phinx already has a solution for it?

> The thing is: if I keep that initial migration in the db/migrations directory and try to run the migrations in an environment where the DB schema already is setup, the script will fail, with an error saying "table xyz already exists".

Exactly for this reason, phinx stores all executed versions in the `phinxlog` table. When you start the `phinx migrate` command again, it will look for new migration files and starts from the latests version. So an error like `table x already exists` should not happen.

If your initial schema sql contains only the table structure, then the `phinxlog` table is empty and phinx will run all the existing migrations. This would fail, of course, because the tables already exists and phinx is not "in sync" with your actual schema. 

I think that this package (and phinx + any other migration tool) is not built for your use case. I would try to look for another solution if you want to keep your use case.
