### ISSUE TITLE
Ive generated a default, now what?

### ISSUE THREAD

**Issue by MACscr** [odan/phinx-migrations-generator#7]
Apologies for my ignorance as I have no experience with your solution or phinx until now, but how should i go about using your solution after Ive generated the default schema, and initial '20170308233115_Test.php', etc? 

Can I know make changes directly to the mysql db schema and then run your generator to create a new file with the alterations?

How should I go about implementing those alterations using your solution on a new db that needs its  schema migrated to the new on that i generated?

Thanks for your time and patience. I truly appreciate it.

**Comment by MACscr** [comment]
Ah, ok, so when I run the generation, it does indeed create a new schema and migration file. Now I guess I just have to figure out how to use those migration files. lol

**Comment by odan** [comment]
Hi, you can use the [Phinx](https://phinx.org/) `migrate` command to run the generated migration files.

http://docs.phinx.org/en/latest/commands.html#the-migrate-command

**Comment by MACscr** [comment]
Do I just use the name that was set using your tool? Like phinx migrate -e test? Do I need to go through all the phinx init and setup process first or does your tool take care of that?

- Mark

**Comment by odan** [comment]
This tool is no 'wrapper' for phinx, it's a just replacement for the lazy `phinx create MyNewMigration` command.  The problem is that Phinx cannot generate migrations automatically. Phinx "only" generates an empty class with up() and down() class methods. You still have to write the migration manually. This tool is trying to fill the gap. Instead of calling the `phinx create` command you call the `phinx-migrations generate` command. 

> Do I need to go through all the phinx init and setup process first or does your tool take care of that?
Both tools run separately and must also be configured separately. This tool does not take care of the phinx settings (until now). Currently, an extra config file is necessary.

But, you know what? I try to implement a new feature to respect the current phinx settings and drop the extra config file. I'm not sure if it works, but I can try it.

**Comment by lunetics** [comment]
Sounds neat! new to phinx and your tool helps alot.

**Comment by odan** [comment]
The new version (1.0.0) uses the phinx configuration and environment settings. Please try it. I am looking forward to your feedback.
