### ISSUE TITLE
Question: What is the purpose of the initial migration file?

### ISSUE THREAD

**Issue by jonneroelofs** [odan/phinx-migrations-generator#8]
Could you tell me what the purpose is of the initial migration file? To what is it comparing the current schema?

I ask because it generates a migration file that I cannot run because it contains migration commands that are already in my schema. 

I'm probably missing something.

Great tool btw!

**Comment by odan** [comment]
Hi! 

The `schema.php` file contains the database schema since the last time you have called the "generate" command. Everytime you call the "generate" command, this tools compares the current (local) database tables and fields with the schema definitions in `schema.php`. Based on the difference, a new phinx migrations class is generated. After that you can make changes in the database and run the "migrate" command again to generate the next phinx migration class. The new phinx migration class contains only the difference from the last migration. You can repeat this steps as long as you want. You should also put the `schema.php` and the generated phinx classes under version control (git, svn).

Today I added a new feature. Everytime you generate a new migration, the new migration is getting marked as migrated. This is necessary because your local database is already in that schema version. This should fix this issue with new migrations. The feature is available at version 1.2.0.

**Comment by jonneroelofs** [comment]
Hi Daniel,

Thanks for you explanation. Great new feature. That feature actually solves a lot of what I was confused about. 

I do still wonder about the very first time you run the generate command. Should that not generate only the schema and no migration? Because it seems to me that the very first time you take the entire schema as the baseline and from that baseline there are no changes at that point. What is your view on this?

Cheers,

Jonne

**Comment by odan** [comment]
The `generate` command is for the developer only and generates the phinx migrations classes for you. If you want to run the migration itself you must call the phinx `migrate` command (on the server). The first time you run the `generate` command you have no `schema.php` and the tool generates an inital / setup schema for you. This is necessary because you have an empty database if you deploy the application for the first time (on the test/staging/prod server). phinx itself just runs all the generated migration scripts (classes) one after another.

**Comment by jonneroelofs** [comment]
Thanks I see what you mean now. I was thinking of the scenario where the other servers have the same base schema as the point in time when I run generate for the first time.

**Comment by sizeg** [comment]
> You should also put the `schema.php` and the generated phinx classes under version control (git, svn).

@odan hello! Every developer has it's own database name, so 'TABLE_SCHEMA' generated in file will be differ. For example if I commit my schema.php it will override for others. What should I do in that case? Ignore schema.php from repository?

**Comment by odan** [comment]
Hi @sizeg The purpose of `schema.php` is to commit this file to the repository. The  `TABLE_SCHEMA` value is realy not necessary. The best solution would be to remove this value from schema.php. I will have a look at it. Maybe create a new issue for this.
